### ISSUE TITLE
Unhandled exception when proxy spits garbage

### ISSUE THREAD

**Issue by dimaqq** [liris/websocket-client#138]
```py
DEBUG:root:Connecting proxy...
Traceback (most recent call last):
  File "scripts/red.py", line 153, in <module>
    ws, current_event_id = connect(url)
  File "scripts/red.py", line 69, in connect
    ws.connect(url, **proxy)
  File "/dima/plc/lib/python2.7/site-packages/websocket/_core.py", line 506, in connect
    self._tunnel(hostname, port, proxy_auth)
  File "/dima/plc/lib/python2.7/site-packages/websocket/_core.py", line 541, in _tunnel
    status, resp_headers = self._read_headers()
  File "/dima/plc/lib/python2.7/site-packages/websocket/_core.py", line 649, in _read_headers
    status = int(status_info[1])
IndexError: list index out of range
```

tested using websocket-client==0.23.0 again this manual "proxy":

```sh
[dima@bmg ~]$ nc -vlp 1080
Connection from 127.0.0.1:48237
CONNECT events-qa.somewhere.com:8899 HTTP/1.0
Proxy-Authorization: Basic aGFoYWFoOjU3MjMyOjM0NjQ=

cfgdf<enter><enter>  # my input
```

**Comment by dimaqq** [comment]
```py
In [20]: ws.connect("wss://google.com/foobar", http_proxy_host="::", http_proxy_port=8080, http_proxy_auth="u:p")
Connecting proxy...
--- request header ---
CONNECT google.com:443 HTTP/1.0
Proxy-Authorization: Basic dTo6


-----------------------
--- response header ---
foobar
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-20-c9fc36b245e7> in <module>()
----> 1 ws.connect("wss://google.com/foobar", http_proxy_host="::", http_proxy_port=8080, http_proxy_auth="u:p")

/dima/plc/lib/python2.7/site-packages/websocket/_core.pyc in connect(self, url, **options)
    504 
    505         if proxy_host:
--> 506             self._tunnel(hostname, port, proxy_auth)
    507 
    508         if is_secure:

/dima/plc/lib/python2.7/site-packages/websocket/_core.pyc in _tunnel(self, host, port, auth)
    539         self._send(connect_header)
    540 
--> 541         status, resp_headers = self._read_headers()
    542         if status != 200:
    543             raise WebSocketException("failed CONNECT via proxy")

/dima/plc/lib/python2.7/site-packages/websocket/_core.pyc in _read_headers(self)
    647             if not status:
    648                 status_info = line.split(" ", 2)
--> 649                 status = int(status_info[1])
    650             else:
    651                 kv = line.split(":", 1)

IndexError: list index out of range

```

Here server responded with `foobar` instead of `HTTP/1.1 200 OK`

Client crashes because server response doesn't contain a space, and thus doesn't have 2nd token in response line.

**Comment by liris** [comment]
I don't understand  why the response body is "foobar", not http satatus line.
The response doesn't look http protocol. Can I reproduce this with opensource proxy server?

**Comment by dimaqq** [comment]
No, it cannot happen with a proper, compliant server.

It's only a problem in the following scenario:
* user puts wrong proxy host or port
* something else (not http) runs on that address
* response that server is rubbish

I think same error will show up if server closes connection without any response too.

Another case is if server response is random rubbish and `line = line.decode('utf-8')` fails.

Current `_tunnel(...)` code looks like this:
```py
        status, resp_headers = self._read_headers()
        if status != 200:
            raise WebSocketException("failed CONNECT via proxy")
```

I suggest to convert other errors to `WebSocketException` in addition to `status != 200`.

You have a valid point that it's not really websocket-client's business to deal with utterly broken servers.

It's your call.

**Comment by liris** [comment]
I got your point.
We should take care of proxy error status more friendly.
