### ISSUE TITLE
OSError: [Errno 14] Bad address

### ISSUE THREAD

**Issue by miohtama** [liris/websocket-client#149]
I am getting the following error when calling `send()` every time on this certain system:

    Traceback (most recent call last):
      File "/srv/django/tatianastore/venv/src/pusherclient/pusherclient/connection.py", line 189, in send_event
        self.socket.send(json.dumps(event).encode("utf-8"))
      File "/srv/django/tatianastore/venv/lib/python3.4/site-packages/websocket/_app.py", line 97, in send
        if not self.sock or self.sock.send(data, opcode) == 0:
      File "/srv/django/tatianastore/venv/lib/python3.4/site-packages/websocket/_core.py", line 675, in send
        return self.send_frame(frame)
      File "/srv/django/tatianastore/venv/lib/python3.4/site-packages/websocket/_core.py", line 701, in send_frame
        l = self._send(data)
      File "/srv/django/tatianastore/venv/lib/python3.4/site-packages/websocket/_core.py", line 912, in _send
        return self.sock.send(data)
      File "/usr/lib/python3.4/ssl.py", line 679, in send
        v = self._sslobj.write(data)
    OSError: [Errno 14] Bad address

According to Googling research, the scary error `[Errno 14] Bad address` indicates that there is some underlying failure in SSL stack or Python socket library. 

Unit tests pass on this computer.

Stack

- Python 3.4.1

- Ubuntu 12.04

- websocket-client git master

- PusherClient: https://github.com/ekulyk/PythonPusherClient

I am out of the ideas what could cause this, so I just document the issue here and hope somebody else comes across this, so we can have more input.

**Comment by miohtama** [comment]
Hmm, might be underlying OpenSSL bug. Ruby folks are having similar issues: https://github.com/excon/excon/issues/467

**Comment by liris** [comment]
I haven't seen this before.
It looks the specific issue of openssl 1.0.2. Are you using openssl 1.0.2?

**Comment by miohtama** [comment]
OpenSSL is 1.0.1-4ubuntu5.20 - still investigating this

**Comment by liris** [comment]
Thanks for your information.

http://rt.openssl.org/Ticket/Display.html?id=3739

**Comment by miohtama** [comment]
Closing this issue - there is now new OpenSSL release.
