### ISSUE TITLE
Keep connection open

### ISSUE THREAD

**Issue by Grief-Code** [liris/websocket-client#154]
Hey im trying to use the websocket as plugin for my system.

However, It only send once a message, because the timespan between the first message and the other messages is longer than some minutes.
I tried it so far with this script:
```python
import host
import websocket
import thread

# Placeholder for the websocket
hostname = ""
port = ""
pw = ""
roomid = "1"
roomname = "OHC ROOM 1"

def init( ):
        host.registerHandler("StartUp",sendConnect)
        host.registerHandler("GameCreated", sendCreate)
        host.registerHandler("GameEnded", sendEnd)

def deinit():
        global ws
        ws.close( );
        print("OHConnect websocket closed")

def sendConnect( CFG ):
        global ws, hostname, port, pw

        hostname = CFG.getString("ohc_ip", "")
        port = CFG.getString("ohc_port", "")
        pw = CFG.getString("ohc_pass", "")

        ws = websocket.WebSocket()
        ws.connect("ws://"+hostname+":"+port)
        print("Connecting to OHConnect websocket on "+hostname+":"+port)
        toSend = "{\"user\":\"OHC Bot\",\"newuser\":\"OHC Bot\",\"message\":\"\",\"ip\":\"\",\"room\":\""+roomid+"\", \"roomname\": \""+roomname+"\", \"pid\": \"\", \"color\":\"#FF0808\", \"l\": \"10\", \"pw\": \""+pw+"\"}"
        ws.send(toSend)

def sendCreate( cGame ):
        msg = "Created a new game: " + cGame.getGameName(  )
        sendMessage( msg )

def sendEnd( cGame ):
        msg = "Finished game: " + cGame.getGameName( )
        sendMessage( msg )

def sendMessage( message ):
        global pw, ws
        toSend = "{\"type\":\"usermsg\", \"datetime\":\"\", \"user\": \"OHC Bot\", \"message\":\""+message+"\", \"text\":\""+message+"\",\"color\":\"#FF0808\", \"l\": \"10\", \"room\": \""+roomid+"\", \"roomname\":\""+roomname+"\", \"pw\":\""+pw+"\"}"
        print(toSend)
        ws.send(toSend)
```

Probably the connection seems to be closed after around ~1 minute:
```
[PLUGIN] Traceback (most recent call last):
[PLUGIN]   File "./plugins/ohconnect/_core.py", line 38, in sendEnd
[PLUGIN]     sendMessage( msg )
[PLUGIN]   File "./plugins/ohconnect/_core.py", line 44, in sendMessage
[PLUGIN]     ws.send(toSend)
[PLUGIN]   File "./plugins/ohconnect/websocket/_core.py", line 686, in send
[PLUGIN]     return self.send_frame(frame)
[PLUGIN]   File "./plugins/ohconnect/websocket/_core.py", line 712, in send_frame
[PLUGIN]     l = self._send(data)
[PLUGIN]   File "./plugins/ohconnect/websocket/_core.py", line 923, in _send
[PLUGIN]     return self.sock.send(data)
[PLUGIN] socket.error: [Errno 32] Broken pipe
```

Is there any way to avoid using WebsocketApp as only persistent connection?
The WebsocketApp is probably influencing the main thread.

**Comment by liris** [comment]
Which OS are you using for client ? and How long do you set to the server connection timeout?
I think TCP connection timeout is too short.

**Comment by Grief-Code** [comment]
The server is running on Ubuntu 14.04, as PHP Websocket Server.
The client is running as well on Ubuntu 14.04, written in cpython and integrated into a C++ Application with boost::python.

What is the recommend timeout?
I think we are using 30 seconds.


A bad workaround is to always create a new connection on every message which need to be send and then close it. But that wouldnt work for a lostening option. And the way actually is stupid.

**Comment by liris** [comment]
Do you have HTTP server in the front of PHP Websocket Server?

I want to figure out who disconnet the connection.  Can you send "ping" message every 10 sec?

**Comment by Grief-Code** [comment]
Yea i got a php server in front of the websocket.

I will leave more information when i have tested it.

**Comment by Grief-Code** [comment]
Sorry it took a bit time.

Issue is still present, also when sending a ping each 10 seconds.

```python
def onUpdate( cGHost ):
        global lastPingTime

        if gettime() - lastPingTime >= 10000:
                print("Send Ping")
                ws.ping()
                lastPingTime = gettime()

def gettime():
        return int(round(time.time() * 1000))
```
