### ISSUE TITLE
Tests fail when not connected to the network

### ISSUE THREAD

**Issue by anthonyryan1** [liris/websocket-client#155]
When running the tests without being connected to a network (except for the localhost/loopback interface) several of the tests in the suite fail. Connecting to the network again makes these tests pass.

```
======================================================================
ERROR: testSockOpt (websocket.tests.test_websocket.SockOptTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/websocket-client-0.25.0/work/websocket-client-0.25.0/websocket/tests/test_websocket.py", line 530, in testSockOpt
    s = ws.create_connection("ws://echo.websocket.org", sockopt=sockopt)
  File "/var/tmp/portage/dev-python/websocket-client-0.25.0/work/websocket-client-0.25.0/websocket/_core.py", line 270, in create_connection
    websock.connect(url, **options)
  File "/var/tmp/portage/dev-python/websocket-client-0.25.0/work/websocket-client-0.25.0/websocket/_core.py", line 478, in connect
    addrinfo_list = socket.getaddrinfo(hostname, port, 0, 0, socket.SOL_TCP)
socket.gaierror: [Errno -3] Temporary failure in name resolution

======================================================================
ERROR: testAfterClose (websocket.tests.test_websocket.WebSocketTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/websocket-client-0.25.0/work/websocket-client-0.25.0/websocket/tests/test_websocket.py", line 440, in testAfterClose
    s = ws.create_connection("ws://echo.websocket.org/")
  File "/var/tmp/portage/dev-python/websocket-client-0.25.0/work/websocket-client-0.25.0/websocket/_core.py", line 270, in create_connection
    websock.connect(url, **options)
  File "/var/tmp/portage/dev-python/websocket-client-0.25.0/work/websocket-client-0.25.0/websocket/_core.py", line 478, in connect
    addrinfo_list = socket.getaddrinfo(hostname, port, 0, 0, socket.SOL_TCP)
socket.gaierror: [Errno -3] Temporary failure in name resolution

======================================================================
ERROR: testPingPong (websocket.tests.test_websocket.WebSocketTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/websocket-client-0.25.0/work/websocket-client-0.25.0/websocket/tests/test_websocket.py", line 404, in testPingPong
    s = ws.create_connection("ws://echo.websocket.org/")
  File "/var/tmp/portage/dev-python/websocket-client-0.25.0/work/websocket-client-0.25.0/websocket/_core.py", line 270, in create_connection
    websock.connect(url, **options)
  File "/var/tmp/portage/dev-python/websocket-client-0.25.0/work/websocket-client-0.25.0/websocket/_core.py", line 478, in connect
    addrinfo_list = socket.getaddrinfo(hostname, port, 0, 0, socket.SOL_TCP)
socket.gaierror: [Errno -3] Temporary failure in name resolution

======================================================================
ERROR: testWebSocket (websocket.tests.test_websocket.WebSocketTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/websocket-client-0.25.0/work/websocket-client-0.25.0/websocket/tests/test_websocket.py", line 391, in testWebSocket
    s = ws.create_connection("ws://echo.websocket.org/")
  File "/var/tmp/portage/dev-python/websocket-client-0.25.0/work/websocket-client-0.25.0/websocket/_core.py", line 270, in create_connection
    websock.connect(url, **options)
  File "/var/tmp/portage/dev-python/websocket-client-0.25.0/work/websocket-client-0.25.0/websocket/_core.py", line 478, in connect
    addrinfo_list = socket.getaddrinfo(hostname, port, 0, 0, socket.SOL_TCP)
socket.gaierror: [Errno -3] Temporary failure in name resolution

======================================================================
ERROR: testWebSocketWihtCustomHeader (websocket.tests.test_websocket.WebSocketTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/websocket-client-0.25.0/work/websocket-client-0.25.0/websocket/tests/test_websocket.py", line 431, in testWebSocketWihtCustomHeader
    headers={"User-Agent": "PythonWebsocketClient"})
  File "/var/tmp/portage/dev-python/websocket-client-0.25.0/work/websocket-client-0.25.0/websocket/_core.py", line 270, in create_connection
    websock.connect(url, **options)
  File "/var/tmp/portage/dev-python/websocket-client-0.25.0/work/websocket-client-0.25.0/websocket/_core.py", line 478, in connect
    addrinfo_list = socket.getaddrinfo(hostname, port, 0, 0, socket.SOL_TCP)
socket.gaierror: [Errno -3] Temporary failure in name resolution

======================================================================
FAIL: testKeepRunning (websocket.tests.test_websocket.WebSocketAppTest)
A WebSocketApp should keep running as long as its self.keep_running
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/websocket-client-0.25.0/work/websocket-client-0.25.0/websocket/tests/test_websocket.py", line 495, in testKeepRunning
    WebSocketAppTest.NotSetYet))
AssertionError: True is not false

======================================================================
FAIL: testSockMaskKey (websocket.tests.test_websocket.WebSocketAppTest)
A WebSocketApp should forward the received mask_key function down
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/websocket-client-0.25.0/work/websocket-client-0.25.0/websocket/tests/test_websocket.py", line 523, in testSockMaskKey
    self.assertEqual(WebSocketAppTest.get_mask_key_id, id(my_mask_key_func))
AssertionError: <websocket.tests.test_websocket.WebSocketAppTest.NotSetYet object at 0x7fa33956df50> != 140339018202144

```

**Comment by liris** [comment]
3ed5784a8e93c9c9965fd80df2a04fc2aba5fd26
