### ISSUE TITLE
python 2.7.9: ssl.SSLError: [SSL: PARSE_TLSEXT] parse tlsext (_ssl.c:590)

### ISSUE THREAD

**Issue by dpb1** [liris/websocket-client#174]
This is on Ubuntu Vivid which has python 2.7.9.  I have a websocket endpoint I'm trying to connect to, it works in python 3.4.3, but when tried with 2.7, I get the following:

```
dpb@helo:~[0]$ python2 websocket-test.py
Traceback (most recent call last):
  File "websocket-test.py", line 15, in <module>
    ws = websocket.create_connection("wss://10.96.4.46:17070", sslopt=sslopt)
  File "/usr/lib/python2.7/dist-packages/websocket/_core.py", line 104, in create_connection
    websock.connect(url, **options)
  File "/usr/lib/python2.7/dist-packages/websocket/_core.py", line 253, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options))
  File "/usr/lib/python2.7/dist-packages/websocket/_http.py", line 69, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/usr/lib/python2.7/dist-packages/websocket/_http.py", line 149, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname)
  File "/usr/lib/python2.7/dist-packages/websocket/_http.py", line 135, in _wrap_sni_socket
    server_hostname=hostname,
  File "/usr/lib/python2.7/ssl.py", line 352, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 579, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 808, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: PARSE_TLSEXT] parse tlsext (_ssl.c:590)
dpb@helo:~[0]$ python3 websocket-test.py
dpb@helo:~[0]$
```

Here is the script contents that reproduces the issue:

```
import ssl
import websocket

sslopt = {
    "ssl_version": ssl.PROTOCOL_TLSv1,
    "ca_certs": "/home/dpb/cert.pem",
    "check_hostname": False}

ws = websocket.WebSocket()
ws = websocket.create_connection("wss://10.96.4.46:17070", sslopt=sslopt)
```

This is using HEAD as of 3bc1fcdb79751c84f7a5ce283da1deac51d44b7f

**Comment by liris** [comment]
This looks a different issue from #175 .

**Comment by liris** [comment]
I cannot reproduce this issue...

**Comment by dpb1** [comment]
Thanks, I'll try to build a more isolated/reproduceable test.  Will Close for now.
