### ISSUE TITLE
Python 2.7.9: ValueError: Cannot set verify_mode to CERT_NONE when check_hostname is enabled.

### ISSUE THREAD

**Issue by dpb1** [liris/websocket-client#175]
Similar to #174 (same environment, etc):

```
dpb@helo:~[0]$ python2.7 websocket-test.py
Traceback (most recent call last):
  File "websocket-test.py", line 15, in <module>
    ws = websocket.create_connection("wss://10.96.4.46:17070", sslopt=sslopt)
  File "/usr/lib/python2.7/dist-packages/websocket/_core.py", line 104, in create_connection
    websock.connect(url, **options)
  File "/usr/lib/python2.7/dist-packages/websocket/_core.py", line 253, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options))
  File "/usr/lib/python2.7/dist-packages/websocket/_http.py", line 69, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/usr/lib/python2.7/dist-packages/websocket/_http.py", line 149, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname)
  File "/usr/lib/python2.7/dist-packages/websocket/_http.py", line 128, in _wrap_sni_socket
    context.verify_mode = sslopt['cert_reqs']
ValueError: Cannot set verify_mode to CERT_NONE when check_hostname is enabled.
dpb@helo:~[0]$ python3 websocket-test.py
dpb@helo:~[0]$
```

Reproduction test case:

```
import ssl
import websocket

sslopt = {
    "ssl_version": ssl.PROTOCOL_TLSv1,
    "check_hostname": False,
    "cert_reqs": ssl.CERT_NONE}

ws = websocket.WebSocket()
ws = websocket.create_connection("wss://10.96.4.46:17070", sslopt=sslopt)
```

**Comment by KenjiTakahashi** [comment]
This looks like my fault. I did not think that a property setter will have such a side effect and it is not clearly stated in the docs that it does... Kinda funny that it works with PY3.
Anyway, I'll try to fix that sometime tomorrow if nobody comes around sooner.

**Comment by KenjiTakahashi** [comment]
Damn, GitHub, why U do dis?
