### ISSUE TITLE
TypeError: cafile, capath and cadata cannot be all omitted

### ISSUE THREAD

**Issue by t3zla** [liris/websocket-client#227]
I get this error when I try to use websocket.create_connection:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/python3.5/site-packages/hackchat.py", line 17, in __init__
        self.ws = websocket.create_connection("wss://hack.chat/chat-ws")
      File "/usr/lib/python3.5/site-packages/websocket/_core.py", line 104, in create_connection
        websock.connect(url, **options)
      File "/usr/lib/python3.5/site-packages/websocket/_core.py", line 266, in connect
        self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options))
      File "/usr/lib/python3.5/site-packages/websocket/_http.py", line 69, in connect
        sock = _ssl_socket(sock, options.sslopt, hostname)
      File "/usr/lib/python3.5/site-packages/websocket/_http.py", line 163, in _ssl_socket
        sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
      File "/usr/lib/python3.5/site-packages/websocket/_http.py", line 128, in _wrap_sni_socket
        context.load_verify_locations(cafile=sslopt.get('ca_certs', None))
    TypeError: cafile, capath and cadata cannot be all omitted

It works on my debian machine using python 3.4

**Comment by liris** [comment]
try  sslopt['cert_reqs'] = CERT_NONE .

**Comment by t3zla** [comment]
Where would I put that?

**Comment by john-tho** [comment]
I had the same error and seemed to be able to get around it by specifying the system cafile.
I don't know how valid this it.
```python
import websocket
import ssl
ssl_defaults = ssl.get_default_verify_paths()
sslopt_ca_certs = {'ca_certs': ssl_defaults.cafile}
wss = websocket.WebSocket(sslopt=sslopt_ca_certs)
wss.connect('wss://echo.websocket.org')
```

**Comment by liris** [comment]
I got the same error on my python 3.4 env if I set ca_certs

**Comment by liris** [comment]
I treid the following and it work on python 3.5.1.

```python

import websocket
import ssl

sslopt_ca_certs = {'ca_certs': 'websocket/cacert.pem'}
wss = websocket.WebSocket(sslopt=sslopt_ca_certs)
wss.connect('wss://echo.websocket.org')
```
