### ISSUE TITLE
SSL EOF Error

### ISSUE THREAD

**Issue by JosefKuchar** [liris/websocket-client#251]
Hello,
I'm getting this error. I think It is problem with TLSv1. Can you Help me?
`Traceback (most recent call last):
  File "C:\Users\Josef\Desktop\test2.py", line 5, in <module>
    ws = websocket.create_connection("wss://176.9.72.105:475")
  File "C:\Users\Josef\AppData\Local\Programs\Python\Python35\lib\site-packages\websocket\_core.py", line 489, in create_connection
    websock.connect(url, **options)
  File "C:\Users\Josef\AppData\Local\Programs\Python\Python35\lib\site-packages\websocket\_core.py", line 216, in connect
    options.pop('socket', None))
  File "C:\Users\Josef\AppData\Local\Programs\Python\Python35\lib\site-packages\websocket\_http.py", line 73, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "C:\Users\Josef\AppData\Local\Programs\Python\Python35\lib\site-packages\websocket\_http.py", line 169, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "C:\Users\Josef\AppData\Local\Programs\Python\Python35\lib\site-packages\websocket\_http.py", line 154, in _wrap_sni_socket
    server_hostname=hostname,
  File "C:\Users\Josef\AppData\Local\Programs\Python\Python35\lib\ssl.py", line 376, in wrap_socket
    _context=self)
  File "C:\Users\Josef\AppData\Local\Programs\Python\Python35\lib\ssl.py", line 747, in __init__
    self.do_handshake()
  File "C:\Users\Josef\AppData\Local\Programs\Python\Python35\lib\ssl.py", line 983, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Users\Josef\AppData\Local\Programs\Python\Python35\lib\ssl.py", line 628, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:645)`

**Comment by liris** [comment]
I'm not sure because this is TLS issue, not websocket issue.

**Comment by czheo** [comment]
same issue

**Comment by achuthman** [comment]
Josef , how did you get past this EOF error . I see the same error with protocol TLSv1_2 even when SSL ciphers are passed along with certificates during the websocket connection
